language: java
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install -y gnupg rng-tools
  - sudo rngd -r /dev/urandom
  - sudo ./gen-key.sh
  - ./test-launch-etcd.sh v2.2.5
  - mvn update

# add env var to detect it during build
env: TRAVIS=true
sudo: required
